### ISSUE TITLE
Gradle依赖怎么感觉不行，添加进去会报错。还是我studio有问题？

### ISSUE THREAD

**Issue by dazai007** [ssseasonnn/PracticalRecyclerView#1]

**Comment by xm3366336** [comment]
可以啊，我能用
compile 'zlc.season:practicalrecyclerview:1.0.3'

**Comment by ssseasonnn** [comment]
@dazai007 
之前的dependencies写错了, 写成了
dependencies{
         compile 'compile 'zlc.season:practicalrecyclerview:1.0.3'
}

改为:
dependencies{
         compile  'zlc.season:practicalrecyclerview:1.0.3'
}
就可以了
